name: build-release
on:
  push:
    tags:
      - '**'
env:
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  OOSRH_USERNAME: ${{ secrets.OOSRH_USERNAME }}
  OOSRH_PASSWORD: ${{ secrets.OOSRH_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          server-id: ossrh
          server-username: OOSRH_USERNAME
          server-password: OOSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_KEY_SECRET }}
          gpg-passphrase: GPG_PASSPHRASE
          cache: 'maven'
      - name: Deploy release
        run: mvn deploy -DskipTests -Prelease
      - name: Create release
        uses: lorislab/changelog-action@v1.0.0
        with:
          args: generate --create-release --close-version --file .github/changelog.yaml
        env:
          CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
